name=audio-driver
version=0.3.0
author=Phil Schatzmann
maintainer=Phil Schatzmann
sentence=Audio Codecs
paragraph=Library to manage many Audio Codecs
category=Signal Input/Output
url=https://github.com/pschatzmann/arduino-audio-driver
architectures=*
depends=
